src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    const ROLE_ADMIN = 'ROLE_ADMIN';
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password

     * @ORM\Column(type="string")
     */
    private $password;

    /**
      * @var string The hashed password

      * @ORM\Column(type="string")
      */
   
    private $isVerified = false;
    /**
    * @ORM\Column(type="boolean")
    */
    private $etat = false;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Societe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $siteweb;

  

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

   

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getSociete(): ?string
    {
        return $this->Societe;
    }

    public function setSociete(string $Societe): self
    {
        $this->Societe = $Societe;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSiteweb(): ?string
    {
        return $this->siteweb;
    }

    public function setSiteweb(string $siteweb): self
    {
        $this->siteweb = $siteweb;

        return $this;
    }
    public function isAdmin(): bool
    {
        return  in_array(self::ROLE_ADMIN, $this->getRoles());
    }


    /**
    * @return mixed
    */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat): void
    {
        $this->etat = $etat;
    }
}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\LocaleType;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email',EmailType::class, ['label' => 'Email','attr'=>['class'=> 'form-control']])
            ->add('roles')
            ->add('password')
            ->add('isVerified')
            ->add('etat')
            ->add('description',TextType::class, ['label' => 'Description','attr'=>['class'=> 'form-control']])
            ->add('lastname',TextType::class, ['label' => 'Nom','attr'=>['class'=> 'form-control']])
            ->add('Firstname',TextType::class, ['label' => 'Prénom','attr'=>['class'=> 'form-control']])
            ->add('pays',TextType::class, ['label' => 'Pays','attr'=>['class'=> 'form-control']])
            ->add('Societe',TextType::class, ['label' => 'Société','attr'=>['class'=> 'form-control']])
            ->add('adresse',TextType::class, ['label' => 'Adresse','attr'=>['class'=> 'form-control']])
            ->add('siteweb',TextType::class, ['label' => 'Site web','attr'=>['class'=> 'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UsersRepository $usersRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $usersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new Users();
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, Users $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
    /**
    * @Route("/bloq/{id}", name="users_bloq")
    */
    public function bloq(Users $user)
    {
        if ($user->getEtat() == true) {
            $user->setEtat(false);
        } else {
            $user->setEtat(true);
        }
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();
        return $this->redirectToRoute('user_index');
    }

}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Images;
use App\Form\EditProfileType;
use App\Service\ManagePicturesService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Component\HttpFoundation\Response;

class UsersController extends AbstractController
{
    /**
     * @Route("/users", name="users")
     */
    public function index(): Response
    {
        return $this->render('users/index.html.twig');
    }
    

    /**
         * @Route("/users/profil/modifier", name="users_profil_modifier")
         */
    public function editprofile(Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(EditProfileType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash('message', 'Profil mis à jour');
            return $this->redirectToRoute('users');
        }

        return $this->render('users/editprofile.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
    * @Route("/users/pass/modifier", name="users_pass_modifier")
    */
    public function editPass(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        if ($request->isMethod('POST')) {
            $em = $this->getDoctrine()->getManager();

            $user = $this->getUser();

            // On vérifie si les 2 mots de passe sont identiques
            if ($request->request->get('pass') == $request->request->get('pass2')) {
                $user->setPassword($passwordEncoder->encodePassword($user, $request->request->get('pass')));
                $em->flush();
                $this->addFlash('message', 'Mot de passe mis à jour avec succès');

                return $this->redirectToRoute('users');
            } else {
                $this->addFlash('error', 'Les deux mots de passe ne sont pas identiques');
            }
        }

        return $this->render('users/editpass.html.twig');
    }
}

templates/users/editpass.html.twig
{% extends 'base1.html.twig' %}
{% block body %}
	<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8">
			<meta http-equiv="X-UA-Compatible" content="IE=edge">
			<title>

				{{app.user.firstname}}
				{{app.user.lastname}}</title>
			<!-- Tell the browser to be responsive to screen width -->
			<meta
			name="viewport" content="width=device-width, initial-scale=1">

			<!-- Font Awesome -->
			<link
			rel="stylesheet" href="../../bundles/plugins/fontawesome-free/css/all.min.css">
			<!-- Ionicons -->
			<link
			rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
			<!-- Theme style -->
			<link
			rel="stylesheet" href="../../bundles/dist/css/adminlte.min.css">
			<!-- Google Font: Source Sans Pro -->
			<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
		</head>
		<!-- Content Wrapper. Contains page content -->
		<div>
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1></h1>
						</div>
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item">
									<a href="/users/">Profil</a>
								</li>
								<li class="breadcrumb-item active">Changer mot de passe</li>
							</ol>
						</div>
					</div>
				</div>
				<!-- /.container-fluid -->
			</section>

			<div class="container">

				<div class="grix xs4">

					<div>
						<div class="col-xs4">

							<div class="grix xs4 container">
								{% for message in app.flashes('error') %}
									<div class="col-xs4">
										<div class="p-3 my-2 rounded-2 error">{{message}}</div>
									</div>
								{% endfor %}
								<div class="col-xs4">
									<h1>Changer mot de passe</h1>
									<form method="post">
										<div class="form-field">
											<label for="pass">Mot de passe</label>
											<input type="password" id="pass" name="pass" class="form-control">
										</div>
										<div class="form-field">
											<label for="pass2">Confirmer mot de passe</label>
											<input type="password" id="pass2" name="pass2" class="form-control">
										</div>
										<div class="form-group">
											<div class="col-xs-12">
												<br>
												<button class="btn btn-lg btn-success pull-right" type="submit">
													<i class="glyphicon glyphicon-ok-sign"></i>
													Modifier</button>
												<!--<button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>-->
											</div>
										</div>

									</form>
								</div>

							</div>

						</html>
					{% endblock %}

templates/users/editprofile.html.twig
{% extends 'base1.html.twig' %}
{% block body %}
	<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8">
			<meta http-equiv="X-UA-Compatible" content="IE=edge">
			<title>

				{{app.user.firstname}}
				{{app.user.lastname}}</title>
			<!-- Tell the browser to be responsive to screen width -->
			<meta
			name="viewport" content="width=device-width, initial-scale=1">

			<!-- Font Awesome -->
			<link
			rel="stylesheet" href="../../bundles/plugins/fontawesome-free/css/all.min.css">
			<!-- Ionicons -->
			<link
			rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
			<!-- Theme style -->
			<link
			rel="stylesheet" href="../../bundles/dist/css/adminlte.min.css">
			<!-- Google Font: Source Sans Pro -->
			<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
		</head>
		<!-- Content Wrapper. Contains page content -->
		<div>
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1></h1>
						</div>
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item">
									<a href="/users/">Profil</a>
								</li>
								<li class="breadcrumb-item active">{{app.user.firstname}}
				{{app.user.lastname}}</li>
							</ol>
						</div>
					</div>
				</div>
				<!-- /.container-fluid -->
			</section>

			<div class="container">
				<div>
					<div class="col-xs4">
						<div class="col-xs4">
							<h1>Modifier profil</h1>
							<div class="col-xs-5">
								<div class="grix xs4">
									{{form(form)}}
										<div>


											<!--/tab-pane-->

										</html>

										<script>

											(function () {
'use strict';
window.addEventListener('load', function () { // Fetch all the forms we want to apply custom Bootstrap validation styles to
var forms = document.getElementsByClassName('needs-validation');
// Loop over them and prevent submission
var validation = Array.prototype.filter.call(forms, function (form) {
form.addEventListener('submit', function (event) {
if (form.checkValidity() === false) {
event.preventDefault();
event.stopPropagation();
}
form.classList.add('was-validated');
}, false);
});
}, false);
})();
										</script>
									</div>
									<!-- /container -->
								</body>
							</html>
						{% endblock %}

templates/users/index.html.twig
{% extends 'base1.html.twig' %}
{% block body %}
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!------ Include the above in your HEAD tag ---------->

	<style>


		body {
			padding-top: 68px;
			padding-bottom: 50px;
		}
		.image-container {
			position: relative;
		}

		.image {
			opacity: 1;
			display: block;
			width: 100%;
			height: auto;
			transition: 0.5s ease;
			backface-visibility: hidden;
		}

		.middle {
			transition: 0.5s ease;
			opacity: 0;
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%, -50%);
			-ms-transform: translate(-50%, -50%);
			text-align: center;
		}

		.image-container:hover .image {
			opacity: 0.3;
		}

		.image-container:hover .middle {
			opacity: 1;
		}
	</style>
	<link rel="stylesheet" href="https://bootswatch.com/4/simplex/bootstrap.min.css"/>
	<div>
		<section class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6"></div>
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item">
								<a href="/admin/">Accueil</a>
							</li>
							<li class="breadcrumb-item active">Profil</li>
						</ol>
					</div>
				</div>
			</div>
			<!-- /.container-fluid -->
		</section>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="card">

						<div class="card-body">
							<div class="card-title mb-4">
								<div class="d-flex justify-content-start">
									<div class="image-container">
										<img src="http://placehold.it/150x150" id="imgProfile" style="width: 150px; height: 150px" class="img-thumbnail"/>
										<div class="middle">
											<input type="button" class="btn btn-secondary" id="btnChangePicture" value="Change"/>
											<input type="file" style="display: none;" id="profilePicture" name="file"/>
										</div>
									</div>
									<div class="userData ml-3">
										<h2 class="d-block" style="font-size: 1.5rem; font-weight: bold">
											<a href="javascript:void(0);">{{ app.user.firstname }}
												{{ app.user.lastname }}</a>
										</h2>

									</div>
									<div class="ml-auto">
										<input type="button" class="btn btn-primary d-none" id="btnDiscard" value="Discard Changes"/>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-12">
									<ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
										<li class="nav-item">
											<a class="nav-link active" id="basicInfo-tab" data-toggle="tab" href="#basicInfo" role="tab" aria-controls="basicInfo" aria-selected="true" class="active">Basic Info</a>
										</li>


									</a>
								</li>
							</ul>
							<div class="tab-content ml-1" id="myTabContent">
								<div class="tab-pane fade show active" id="basicInfo" role="tabpanel" aria-labelledby="basicInfo-tab">


									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Nom</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.firstname }}
										</div>
									</div>
									<hr/>
									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Prénom</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.lastname }}
										</div>
									</div>
									<hr/>

									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Email</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.email }}
										</div>
									</div>
									<hr/>


									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Adresse</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.adresse }}
										</div>
									</div>
									<hr/>
									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Site web</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.siteweb }}
										</div>
									</div>
									<hr/>
									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Sociéte</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.societe }}
										</div>
									</div>
									<hr/>
									<div class="row">
										<div class="col-sm-3 col-md-2 col-5">
											<label style="font-weight:bold;">Pays</label>
										</div>
										<div class="col-md-8 col-6">
											{{ app.user.pays }}
										</div>
									</div>
									<hr/>
									<div class="row">
										<div class="col-12">

											<li class="nav-item">

												<a href="{{ path('users_profil_modifier') }}">Modifier le profil</a>
											</li>
											<li class="nav-item">
												<a href="{{ path('users_pass_modifier')}}">Modifier le mot de passe</a>
											</li>
										</a>
									</li>
								</a>


							</div>
							<div class="tab-pane fade" id="connectedServices" role="tabpanel" aria-labelledby="ConnectedServices-tab">
								Facebook, Google, Twitter Account that are connected to this account
							</div>
						</div>
					</div>
				</div>


			</div>

		</div>
	</div>
</div></div><script>
$(document).ready(function () {
$imgSrc = $('#imgProfile').attr('src');
function readURL(input) {

if (input.files && input.files[0]) {
var reader = new FileReader();

reader.onload = function (e) {
$('#imgProfile').attr('src', e.target.result);
};

reader.readAsDataURL(input.files[0]);
}
}
$('#btnChangePicture').on('click', function () { // document.getElementById('profilePicture').click();
if (!$('#btnChangePicture').hasClass('changing')) {
$('#profilePicture').click();
} else { // change
}
});
$('#profilePicture').on('change', function () {
readURL(this);
$('#btnChangePicture').addClass('changing');
$('#btnChangePicture').attr('value', 'Confirm');
$('#btnDiscard').removeClass('d-none');
// $('#imgProfile').attr('src', '');
});
$('#btnDiscard').on('click', function () { // if ($('#btnDiscard').hasClass('d-none')) {
$('#btnChangePicture').removeClass('changing');
$('#btnChangePicture').attr('value', 'Change');
$('#btnDiscard').addClass('d-none');
$('#imgProfile').attr('src', $imgSrc);
$('#profilePicture').val('');
// }
});
});</script>{% endblock %}